"""
Package for built-in format specifiers, so they can be loaded without loading
the dependencies of the formats.
"""
from ._ADAMSICInputFormatSpecifier import ADAMSICInputFormatSpecifier
from ._ADAMSICOutputFormatSpecifier import ADAMSICOutputFormatSpecifier

from ._ADAMSODInputFormatSpecifier import ADAMSODInputFormatSpecifier
from ._ADAMSODOutputFormatSpecifier import ADAMSODOutputFormatSpecifier

from ._COCOInputFormatSpecifier import COCOInputFormatSpecifier
from ._COCOOutputFormatSpecifier import COCOOutputFormatSpecifier

from ._CommonVoiceInputFormatSpecifier import CommonVoiceInputFormatSpecifier
from ._CommonVoiceOutputFormatSpecifier import CommonVoiceOutputFormatSpecifier

from ._FestVoxInputFormatSpecifier import FestVoxInputFormatSpecifier
from ._FestVoxOutputFormatSpecifier import FestVoxOutputFormatSpecifier

from ._ROIInputFormatSpecifier import ROIInputFormatSpecifier
from ._ROIOutputFormatSpecifier import ROIOutputFormatSpecifier

from ._SubDirInputFormatSpecifier import SubDirInputFormatSpecifier
from ._SubDirOutputFormatSpecifier import SubDirOutputFormatSpecifier

from ._TFRecordsInputFormatSpecifier import TFRecordsInputFormatSpecifier
from ._TFRecordsOutputFormatSpecifier import TFRecordsOutputFormatSpecifier

from ._VGGInputFormatSpecifier import VGGInputFormatSpecifier
from ._VGGOutputFormatSpecifier import VGGOutputFormatSpecifier
