"""
Package specifying the domain of images annotated with objects detected
within those images.
"""
from ._ImageObjectDetectionDomainSpecifier import ImageObjectDetectionDomainSpecifier
from ._ImageObjectDetectionInputConverter import ImageObjectDetectionInputConverter
from ._ImageObjectDetectionOutputConverter import ImageObjectDetectionOutputConverter
from ._ObjectDetectionInstance import ObjectDetectionInstance
