"""
Automatically generated by gen-cli.py.
"""
from argparse import Namespace
from typing import Type

from wai.common.cli import CLIFactory, CLIInstantiable
from wai.common.meta.typing import VAR_ARGS_TYPE

from wai.common.cli.options._ClassOption import ClassOption


class VGGReaderCLIFactory(CLIFactory):
    """
    Factory which instantiates the VGGReader class.
    """
    # Options
    input_files = ClassOption('-I', '--input-files', type=str, action='append', help='Files containing lists of input annotation files (can use glob syntax)')
    inputs = ClassOption('-i', '--inputs', type=str, action='append', help='Input annotations files (can use glob syntax)', metavar='files')
    negative_files = ClassOption('-N', '--negative-files', type=str, action='append', help='Files containing lists of negative images (can use glob syntax)')
    negatives = ClassOption('-n', '--negatives', type=str, action='append', help='Image files that have no annotations (can use glob syntax)', metavar='image')

    @classmethod
    def production_class(self, namespace: Namespace) -> Type[CLIInstantiable]:
        from wai.annotations.vgg.io._VGGReader import VGGReader
        return VGGReader

    @classmethod
    def init_args(self, namespace: Namespace) -> VAR_ARGS_TYPE:
        return (namespace,), dict()
